"USE CLIENT";

IMPORT { USESESSION } FROM "NEXT-AUTH/REACT";
IMPORT { USEROUTER } FROM "NEXT/NAVIGATION";
IMPORT { USEEFFECT } FROM "REACT";
IMPORT { 
  BOX, 
  CONTAINER, 
  FLEX, 
  TEXT 
} FROM "@RADIX-UI/THEMES";

EXPORT DEFAULT FUNCTION HOMEPAGE() {
  CONST { STATUS } = USESESSION();
  CONST ROUTER = USEROUTER();

  

  RETURN (
    <BOX CLASSNAME="MIN-H-SCREEN">
      <CONTAINER SIZE="3" PY="9">
        <FLEX ALIGN="CENTER" JUSTIFY="CENTER" CLASSNAME="MIN-H-[70VH]">
          <TEXT SIZE="3">LOADING...</TEXT>
        </FLEX>
      </CONTAINER>
    </BOX>
  );
}
